[package]
name = "wordcut-server"
version = "0.1.0"
authors = ["Vee Satayamas <vsatayamas@gmail.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-proto = "0.1"
serde_json = "1.0.7"
wordcut-engine = { git="https://github.com/veer66/wordcut-engine" }
lazy_static = "1.0.0"
config = "0.7.0"